#!/bin/bash
set -o nounset
set -o errexit
set -o pipefail

BT2="/home/rmgzshd/bowtie2-2.1.0/bowtie2"
BT2GENOME="/mnt/store1/cghub/KSHV_BT2/HPV"
SAMBAMBA="/home/rmgzshd/sambamba/sambamba"
BEDTOOLS="/home/rmgzshd/bedtools2/bin/bedtools"

export BT2; export BT2GENOME; export SAMBAMBA; export BEDTOOLS;

# We pass through the TCGA BAM file (bwa PE) outputting any unmapped
# tee first to a bed file
# tee second to a grep which pulls out bam reads (ie not header)
# another tee which splits the reads into R1 and R2 fastq files

tee >($BEDTOOLS bamtobed -i stdin > $prefix.ANCHOR.bed )
		>

for bam in *.sorted.bam
do
	prefix=$(echo ${bam} | sed 's/.sorted.bam//')
	$SAMBAMBA view  -F  "(unmapped or mate_is_unmapped) and paired" $bam 			|
	grep -v ^@ |
	tee >(awk 'NR%2==1 {print "@"$1"\n"$10"\n+\n"$11}' > R1.fq) 		> \
		>(awk 'NR%2==0 {print "@"$1"\n"$10"\n+\n"$11}' > R2.fq)			
	

	$SAMBAMBA view --format=bam -F "unmapped or mate_is_unmapped" $bam 	| 
	$BEDTOOLS bamtobed -i stdin > ANCHOR.bed
	
	wait;
# Use bowtie2 to find matches amongst the unmapped genome in HPV 	
	$BT2 -p 24 -x $BT2GENOME -1 R1.fq -2 R2.fq | 
	$SAMBAMBA view -S --format=bam /dev/stdin 	| 
    $BEDTOOLS bamtobed -i stdin > HPV.bed

done

# unix join of ANCHOR.bed and HPV.bed



		
	

