#!/bin/bash
set -o nounset
set -o errexit
set -o pipefail

BT2="/home/rmgzshd/bowtie2-2.1.0/bowtie2"
BT2GENOME="/mnt/store1/cghub/KSHV_BT2/HPV"
SAMBAMBA="/home/rmgzshd/sambamba/sambamba"
BEDTOOLS="/home/rmgzshd/bedtools2/bin/bedtools"

export BT2; export BT2GENOME; export SAMBAMBA; export BEDTOOLS;

# We pass through the TCGA BAM file (bwa PE) outputting any unmapped
# another tee which splits the reads into R1 and R2 fastq files

tee >($BEDTOOLS bamtobed -i stdin > $prefix.ANCHOR.bed )
		>

for bam in *.sorted.bam
do
	# this is giving me a subtly different no. of reads n=4!!!
	prefix=$(echo ${bam} | sed 's/.sorted.bam//')
	time
	(
	$SAMBAMBA view  -F  "unmapped or mate_is_unmapped" $bam 			|
	tee >(awk 'NR%2==1 {print "@"$1"\n"$10"\n+\n"$11}' > R1.fq) 		> \
		>(awk 'NR%2==0 {print "@"$1"\n"$10"\n+\n"$11}' > R2.fq)			
	
	)
	
# THIS WORKS
time(
	$SAMBAMBA view --format=bam -F  "unmapped or mate_is_unmapped" $bam |
	tee >($BEDTOOLS bamtofastq -i stdin -fq R1.fq -fq2 R2.fq)			> \
	tee >($BEDTOOLS bamtobed -i stdin > ANCHOR.bed)
	)


	>$BEDTOOLS bamtofastq -i stdin -fq R1.fq -fq2 R2.fq 
	)

	$SAMBAMBA view --format=bam -F "unmapped or mate_is_unmapped" $bam 	| 
	$BEDTOOLS bamtobed -i stdin > ANCHOR.bed
	
	wait;
# Use bowtie2 to find matches amongst the unmapped genome in HPV 	
	$BT2 -p 24 -x $BT2GENOME -1 R1.fq -2 R2.fq | 
	$SAMBAMBA view -S --format=bam /dev/stdin 	| 
    $BEDTOOLS bamtobed -i stdin > HPV.bed

done

# unix join of ANCHOR.bed and HPV.bed



		
	

